name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  zig-tests:
    runs-on: ubuntu-latest
    name: zig build test (multi version)
    strategy:
      matrix:
        zig-version: [0.15.2]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: zig build test (${{ matrix.zig-version }})
        run: zig build test --summary all

      - name: display zig version
        run: zig version
        if: failure()

  docusaurus-build:
    runs-on: ubuntu-latest
    name: docusaurus build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: "23"

      - name: "npm install"
        run: npm install
        working-directory: website

      - name: "npm run build"
        run: npm run build
        working-directory: website

      - name: "Verify built site"
        run: test website/build
